package amyc
package codegen

import analyzer._
import amyc.ast.Identifier
import amyc.ast.SymbolicTreeModule.{Call => AmyCall, Div => AmyDiv, And => AmyAnd, Or => AmyOr, _}
import amyc.utils.{Context, Pipeline}
import wasm._
import Instructions._
import Utils._

// Generates WebAssembly code for an Amy program
object CodeGen extends Pipeline[(Program, SymbolTable), Module] {
  def run(ctx: Context)(v: (Program, SymbolTable)): Module = {
    val (program, table) = v

    // Generate code for an Amy module
    def cgModule(moduleDef: ModuleDef): List[Function] = {
      val ModuleDef(name, defs, optExpr) = moduleDef
      // Generate code for all functions
      defs.collect { case fd: FunDef if !builtInFunctions(fullName(name, fd.name)) =>
        cgFunction(fd, name, false)
      } ++
      // Generate code for the "main" function, which contains the module expression
      optExpr.toList.map { expr =>
        val mainFd = FunDef(Identifier.fresh("main"), Nil, TypeTree(IntType), expr)
        cgFunction(mainFd, name, true)
      }
    }

    // Generate code for a function in module 'owner'
    def cgFunction(fd: FunDef, owner: Identifier, isMain: Boolean): Function = {
      // Note: We create the wasm function name from a combination of
      // module and function name, since we put everything in the same wasm module.
      val name = fullName(owner, fd.name)
      Function(name, fd.params.size, isMain){ lh =>
        val locals = fd.paramNames.zipWithIndex.toMap
        val body = cgExpr(fd.body)(locals, lh)
        val comment = Comment(fd.toString)
        if (isMain) {
          body <:> Drop // Main functions do not return a value,
                        // so we need to drop the value generated by their body
        } else {
          comment <:> body
        }
      }
    }


    // Generate code for an expression expr.
    // Additional arguments are a mapping from identifiers (parameters and variables) to
    // their index in the wasm local variables, and a LocalsHandler which will generate
    // fresh local slots as required.
    def cgExpr(expr: Expr)(implicit locals: Map[Identifier, Int], lh: LocalsHandler): Code = {
      expr match {
        // Literals
        case BooleanLiteral(b) =>
          Comment(expr.toString) <:> (if (b) Const(1) else Const(0))
        case UnitLiteral() =>
          Comment(expr.toString) <:> Const(0)
        case StringLiteral(s) =>
          mkString(s)
        case IntLiteral(i) =>
          // Push i to the stack.
          // The comments are optional but can help you debug.
          Comment(expr.toString) <:> Const(i)

        // Variables
        case Variable(name) => 
          // Get the local variable corresponding to name
          Comment(expr.toString) <:> GetLocal(locals(name))
          
        // Usual integer operators
        case Plus(lhs, rhs) => 
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Add
        case Minus(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Sub
        case Times(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Mul
        case AmyDiv(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Div
        case Mod(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Rem
        
        // Integer negation
        case Neg(expr) =>
          Comment(expr.toString) <:> Const(0) <:> cgExpr(expr) <:> Sub
        
        // Usual arithmetic comparison operators
        case LessThan(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Lt_s
        case LessEquals(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Le_s

        // Boolean disjuncion and conjunction
        case AmyAnd(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> If_i32 <:> cgExpr(rhs) <:> Else <:> Const(0) <:> End
        case AmyOr(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> If_i32 <:> Const(1) <:> Else <:> cgExpr(rhs) <:> End
        
        // Boolean negation
        case Not(expr) =>
          Comment(expr.toString) <:> cgExpr(expr) <:> Eqz

        // String concatenation operator
        case Concat(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Call("String_concat")

        // Equality operator
        case Equals(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Eq

        // Error
        case Error(msg) =>
          Comment(expr.toString) <:> cgExpr(StringLiteral("Error: ")) <:> cgExpr(msg) <:> Call("String_concat") <:> Call("Std_printString") <:> Unreachable
          
        // If-then-else
        case Ite(cond, thenn, elze) =>
          Comment(expr.toString) <:> cgExpr(cond) <:> If_i32 <:> cgExpr(thenn) <:> Else <:> cgExpr(elze) <:> End
          
        // Sequence operator
        case Sequence(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> Drop <:> cgExpr(rhs)
        
        // Local variable
        case Let(df, value, body) =>
          val fl = lh.getFreshLocal()
          Comment(expr.toString) <:> cgExpr(value) <:> SetLocal(fl) <:> cgExpr(body)(locals + (df.name -> fl), lh)

        // Type or function invocation
        case AmyCall(name, args) =>
          // Check if the call is a constructor or a function
          table.getConstructor(name) match {
            // Constructor
            case Some(constr) =>
              val addr = lh.getFreshLocal()
              // Reserve memory boundary
              val allocCode: Code =
                GetGlobal(memoryBoundary) <:> SetLocal(addr) <:>
                GetGlobal(memoryBoundary) <:> adtField(args.size) <:> SetGlobal(memoryBoundary)
              // Store constructor tag
              val tagCode: Code = GetLocal(addr) <:> Const(constr.index) <:> Store
              
              // Write each field in sequence
              val fullCode: Code = args.zipWithIndex.foldLeft((allocCode <:> tagCode)) {
                case (acc, (arg, idx)) =>
                  acc <:> GetLocal(addr) <:> adtField(idx) <:> cgExpr(arg) <:> Store
              }
              
              Comment(expr.toString) <:> fullCode <:> GetLocal(addr)
            // Function 
            case None => 
              Comment(expr.toString) <:> args.map(cgExpr(_)) <:> Call(fullName(table.getFunction(name).get.owner, name))
          }
          
        // Match pattern
        case Match(scrut, cases) => {

          // Checks if a value matches a pattern.
          // Assumes value is on top of stack (and CONSUMES it)
          // Returns the code to check the value, and a map of bindings.
          def matchAndBind(pat: Pattern): (Code, Map[Identifier, Int]) = {
            pat match {
              case WildcardPattern() =>
                (Comment(pat.toString) <:> Drop <:> Const(1), locals)
              case IdPattern(id) =>
                val idLocal = lh.getFreshLocal()
                (Comment(pat.toString) <:> 
                // Assign val to id.
                SetLocal(idLocal) <:> 
                // Return true (IdPattern always matches).
                Const(1),
                // Let the code generation of the expression which corresponds to this pattern
                // know that the bound id is at local idLocal.
                Map(id -> idLocal))
              case LiteralPattern(lit) =>
                (Comment(pat.toString) <:> cgExpr(lit) <:> Eq, locals)
              case CaseClassPattern(constr, args) =>
                val addr = lh.getFreshLocal()
                // Store scrutinee
                val scr: Code = SetLocal(addr)
                // Constructor tag check
                val tagCheck: Code = GetLocal(addr) <:> Load <:> Const(table.getConstructor(constr).get.index) <:> Eq
                // Match fields and collect bindings
                val (fieldChecks, collectedBindings) = args.zipWithIndex.foldLeft((List.empty[Code], locals)) {
                  case ((codes, binds), (subPat, idx)) =>
                    val loadField = GetLocal(addr) <:> adtField(idx) <:> Load
                    val (subCode, subBinds) = matchAndBind(subPat)
                    (codes :+ (loadField <:> subCode), binds ++ subBinds)
                }
                // Combine field match codes with And
                val argsCheck: Code = fieldChecks match {
                  case Nil => Const(1)
                  case List(single) => single
                  case many => many.reduceLeft(_ <:> _ <:> And)
                }
                
                // Final match code: tag then fields
                val fullCheck: Code = scr <:> tagCheck <:> If_i32 <:> argsCheck <:> Else <:> Const(0) <:> End

                (fullCheck, collectedBindings)
            }
          }
          
          val scrutineeAddress = lh.getFreshLocal()
          // Store the scrutinee
          val initCode: Code = cgExpr(scrut) <:> SetLocal(scrutineeAddress)
          // Generate code for each case
          val casesCode: List[Code] = cases.map { c =>
            val (matchCode, caseLocals) = matchAndBind(c.pat)
            GetLocal(scrutineeAddress) <:> matchCode <:> If_i32 <:> cgExpr(c.expr)(locals ++ caseLocals, lh) <:> Else
          }
          // Default error if no pattern matches
          val defaultCode: Code = mkString("Matching error: ") <:> Call("Std_printString") <:> Unreachable
          // End of the Ite
          val end: List[Code] = cases.map(_ => End)
          
          (initCode :: casesCode ::: List(defaultCode) ::: end).reduceLeft(_ <:> _)
        }
        
        case _ => mkString("Unrecognized expression: " + expr.toString)
      }
    }

    Module(
      program.modules.last.name.name,
      defaultImports,
      globalsNo,
      wasmFunctions ++ (program.modules flatMap cgModule)
    )
  }
}
